source 'http://rubygems.org'

gem 'puppet', '~> 3.1.0'
gem 'hiera-gpg'

group :build do
  gem 'hiera-puppet-helper'
  gem 'librarian-puppet'
  gem 'puppet-lint'
  gem 'puppet-syntax'
  gem 'puppetlabs_spec_helper'
  gem 'rspec-puppet'
end
