forge 'http://forge.puppetlabs.com/'

mod 'puppetlabs/stdlib',           '~> 3.0'
mod 'puppetlabs/razor'
mod 'puppetlabs/git',              '0.0.2'


mod 'jenkins',      :git => 'git://github.com/alphagov/puppet-jenkins.git',
                    :ref => 'ca40459bea5a9dc91e12e8014c9878fcd2856ee7'