# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = 'precise64'
	config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

	config.vm.define "jenkins" do |jenkins|
	config.vm.network "private_network", ip: "10.0.0.10"

	config.vm.synced_folder "..", "/vagrant"

	jenkins.vm.provision :shell,
						path: "../vagrant-bootstrap.sh",
						args: "ci localdev"

	end

end
