#!/usr/bin/env python

import argparse

from birmingham_cabinet.models import *
from birmingham_cabinet.base import Base, engine

def drop_tables():
    Base.metadata.drop_all(engine)
    
def create_tables():
    Base.metadata.create_all(engine)

if __name__ == "__main__":
    drop_tables()
    create_tables()