#!/usr/bin/env python

import argparse

from birmingham_cabinet.models import *
from birmingham_cabinet.base import Base, local_unix_socket_engine

def drop_tables():
    Base.metadata.drop_all(local_unix_socket_engine)

def create_tables():
    Base.metadata.create_all(local_unix_socket_engine)

if __name__ == "__main__":
    drop_tables()
    create_tables()
